name: bluebubbles
description: Send iMessages on Android using BlueBubbles!

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.15.0+70
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.6.0
  animated_size_and_fade: ^4.0.0
  animations: ^2.0.11
  app_links: ^6.1.1
  async_task: ^1.1.1
  audio_waveforms: ^1.0.5
  auto_size_text: ^3.0.0
  bitsdojo_window:
    path: packages/bitsdojo_window_stub
  chunked_stream: ^1.4.2
  collection: ^1.18.0
  confetti: ^0.7.0
  connectivity_plus: ^6.0.2
  crop_your_image: ^1.0.2
  cupertino_icons: ^1.0.6
  defer_pointer: ^0.0.2
  desktop_webview_auth:
    path: packages/desktop_webview_auth_stub
  device_info_plus: ^10.1.0
  dio: ^5.4.2+1
  disable_battery_optimization:
    path: packages/disable_battery_optimization_stub
  dlibphonenumber: ^1.1.12 # phone number parsing
  # todo linux
  dynamic_color: ^1.7.0
  easy_debounce: ^2.0.3
  emojis: ^0.9.9
  emoji_picker_flutter: 3.1.0
  encrypt: ^5.0.3
  exif: ^3.3.0
  faker: ^2.1.0
  fast_contacts:
    path: packages/fast_contacts_stub
  file_picker: ^8.0.0+1
  firebase_dart:
    git:
      url: https://github.com/appsup-dart/firebase_dart.git
      ref: beb79f70a2bb0e96e6bb9fdebac2ff452f138950
      path: packages/firebase_dart
  flex_color_picker: ^3.4.1
  flex_color_scheme: ^7.3.1
  flutter_acrylic:
    path: packages/flutter_acrylic_stub
  flutter_audio_waveforms: ^1.2.1+8
  flutter_displaymode:
    path: packages/flutter_displaymode_stub
  flutter_dotenv: ^5.1.0
  # NEW CRM DEPENDENCIES
  supabase_flutter: ^2.3.4
  fl_chart: ^0.66.0
  flutter_image_compress: ^2.2.0
  flutter_improved_scrolling: ^0.0.3
  flutter_isolate:
    path: packages/flutter_isolate
  flutter_keyboard_visibility: ^6.0.0 # no desktop support
  flutter_local_notifications:
    path: packages/flutter_local_notifications_stub
  flutter_map: ^7.0.1
  flutter_map_marker_popup: ^7.0.0
  flutter_markdown: ^0.7.2+1
  flutter_html: 3.0.0-beta.2
  flutter_quill: ^9.3.3
  quill_delta: ^4.0.0
  flutter_slidable: ^3.1.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  flutter_timezone:
    path: packages/flutter_timezone_stub
  timezone: ^0.9.2
  cached_network_image: ^3.4.1
  geolocator: ^13.0.1
  gesture_x_detector: # support touchscreens properly
    git:
      url: https://github.com/BlueBubblesApp/xgesture_flutter.git
      ref: 7de6e023ff68f67af1d83f7c1303d8b973f84944
  get: ^4.6.6
  giphy_get: ^3.5.4
  github: ^9.24.0
  google_fonts: ^6.2.1
  google_ml_kit:
    path: packages/google_ml_kit_stub
  google_mlkit_smart_reply:
    path: packages/google_mlkit_smart_reply_stub
  google_sign_in: ^6.2.1
  hand_signature: ^3.0.2
  idb_shim: ^2.4.1+1
  image: ^4.1.7
  image_picker: ^1.0.7
  image_size_getter: ^2.1.3
  intl: ^0.19.0
  js: ^0.7.1
  languagetool_textfield: ^0.0.6
  launch_at_startup:
    path: packages/launch_at_startup_stub
  local_auth:
    path: packages/local_auth_stub
  local_notifier:
    path: packages/local_notifier_stub
  provider: ^6.1.2
  maps_launcher: # gradle namespace issue
    git:
      url: https://github.com/pikaju/flutter-maps-launcher.git
      ref: master
  material_color_utilities: ^0.11.1
  media_kit: ^1.1.10+1                           # Primary package.
  media_kit_video: ^1.2.4                        # For video rendering.
  media_kit_native_event_loop: ^1.0.8            # Support for higher number of concurrent instances & better performance.
  media_kit_libs_android_video: ^1.3.6           # Android package for video native libraries.
  media_kit_libs_windows_video: ^1.0.9           # Windows package for video native libraries.
  media_kit_libs_linux: ^1.1.3                   # GNU/Linux dependency package.
  metadata_fetch: ^0.4.1
  mime: ^1.0.5
  mime_type: ^1.0.0
  mobile_scanner:
    path: packages/mobile_scanner_stub
  msix: ^3.16.8
  multi_value_listenable_builder: ^0.0.2
  network_info_plus: ^6.0.1
  network_tools: ^5.0.2
  numberpicker: ^2.1.2
  objectbox: ^4.0.1
  objectbox_flutter_libs: any
  on_exit: ^1.0.0
  open_filex: ^4.4.0
  package_info_plus: ^8.0.0
  particles_flutter: ^1.0.1
  pasteboard: ^0.3.0
  path: ^1.9.0
  path_provider: ^2.1.2 # no web support
  pdf: ^3.10.8
  permission_handler:
    path: packages/permission_handler_stub
  photo_manager:
    path: packages/photo_manager_stub
  photo_view: ^0.15.0
  printing: ^5.12.0
  qr_flutter: ^4.1.0
  receive_intent:
    path: packages/receive_intent_stub
  record: ^5.0.5
  reorderables: ^0.6.0
  saver_gallery: ^3.0.3
  screen_retriever:
    path: packages/screen_retriever_stub
  scroll_to_index: ^3.0.1
  secure_application:  # no linux support, gradle namespace issue
    git:
      url: https://github.com/BlueBubblesApp/secure_application.git
      ref: master
  share_plus: ^10.0.2 # sharing files not supported on Windows & Linux, todo desktop
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  simple_animations: ^5.0.2
  sliding_up_panel2: ^3.3.0+1
  slugify: ^2.0.0
  smooth_page_indicator: ^1.1.0
  socket_io_client: ^2.0.3+1
  sprung: ^3.0.1
  store_checker: ^1.8.0
  synchronized: ^3.1.0+1
  system_tray:
    path: packages/system_tray_stub
  super_drag_and_drop: ^0.8.20
  supercharged: ^2.1.1
  system_info2: ^4.0.0
  tray_manager:
    path: packages/tray_manager_stub
  tuple: ^2.0.2
  unifiedpush: ^5.0.1
  universal_html: ^2.2.4 # cross-platform dart:html implementation
  universal_io: ^2.2.2 # cross-platform dart:io implementation
  url_launcher: ^6.2.5
  vcf_dart: ^1.0.1
  version: ^3.0.2
  video_player: ^2.8.5
  video_thumbnail:
    git:
      url: https://github.com/BlueBubblesApp/video_thumbnail.git
      ref: master
  window_manager:
    path: packages/window_manager_stub
  windows_taskbar:
    path: packages/windows_taskbar_stub
  logger: ^2.4.0
  archive: ^3.6.1
  markdown: ^7.1.1
  in_app_review:
    path: packages/in_app_review_stub
  pull_down_button: ^0.10.1
  app_install_date:
    path: packages/app_install_date_stub

dependency_overrides:
  # overrides for packages stuck on outdated versions
  http: ^1.2.1 # metadata_fetch
  intl: ^0.19.0 # firebase_dart
  js: ^0.7.1 # socket_io_client
  material_color_utilities: ^0.11.1 # flutter test SDK
  permission_handler_platform_interface: ^4.2.1 # BB permission_handler_windows
  permission_handler_windows: # https://github.com/Baseflow/flutter-permission-handler/issues/983
    git:
      url: https://github.com/BlueBubblesApp/flutter-permission-handler.git
      ref: 7912a76a3208e876c2275e1a87003ede3903abc8
      path: permission_handler_windows
  uuid: ^4.4.0 # firebase_dart
  win32: ^5.5.3 # for build issue in flutter v3.24.0
  frontend_server_client: ^4.0.0  # for build_runner issues on v3.24.0

dev_dependencies:
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_lints: ^4.0.0
  analyzer: ^6.5.0
  peanut: ^5.0.0
  objectbox_generator: any
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/adaptive-foreground.png"
  adaptive_icon_background: "#4990de"

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: "assets/icon/splash-foreground-dark.png"
  image_dark: "assets/icon/splash-foreground-dark.png"
  android_12:
    image: "assets/icon/splash-foreground-dark-2.png"
    image_dark: "assets/icon/splash-foreground-dark-2.png"
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "000000"

#   flutter_test:
#     sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # fonts:
  # - family: AppleColorEmoji
  #   fonts:
  #     - asset: assets/fonts/AppleColorEmoji.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/reactions/dislike-white.svg
    - assets/reactions/like-white.svg
    - assets/reactions/emphasize-white.svg
    - assets/reactions/question-white.svg
    - assets/reactions/love-white.svg
    - assets/reactions/dislike-black.svg
    - assets/reactions/like-black.svg
    - assets/reactions/emphasize-black.svg
    - assets/reactions/laugh-black.svg
    - assets/reactions/question-black.svg
    - assets/reactions/love-black.svg
    - assets/icon/moon.svg
    - assets/icon/bb-icon.svg
    - assets/images/google-sign-in.png
    - assets/images/person.png
    - assets/images/person64.png
    - assets/images/transparent.png
    - assets/images/no-video-preview.png
    - assets/images/unplayable-video.png
    - assets/images/Blue-Gradient-Background.png
    - assets/images/text-logo-1320x440.png
    - assets/icon/icon.png
    - assets/icon/contact-photo.png
    - assets/changelog/changelog.md
    - assets/icon/icon.ico
    - assets/badges/badge-1.ico
    - assets/badges/badge-2.ico
    - assets/badges/badge-3.ico
    - assets/badges/badge-4.ico
    - assets/badges/badge-5.ico
    - assets/badges/badge-6.ico
    - assets/badges/badge-7.ico
    - assets/badges/badge-8.ico
    - assets/badges/badge-9.ico
    - assets/badges/badge-10.ico
    - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

msix_config:
  display_name: BlueBubbles
  publisher_display_name: BlueBubbles
  identity_name: 23344BlueBubbles.BlueBubbles
  msix_version: 1.15.0.0
  publisher: CN=BEC9154D-191E-4375-BF30-698BD4C141C4
  vs_generated_images_folder_path: windows/icons
  logo_path: assets/icon/icon.ico
  store: true
  icons_background_color: transparent
  languages: en-us
  architecture: x64
  capabilities: internetClient, location, microphone, webcam
  protocol_activation: imessage
